/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class AdminModHab extends javax.swing.JFrame {
    
    Statement st,zt;
    ResultSet rs,rz;
    Conexion cc = new Conexion();
    Connection cn = cc.conexion();
    PreparedStatement ps;    
    
    public AdminModHab() {
        initComponents();
        this.setLocationRelativeTo(null);           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        NumH = new javax.swing.JTextField();
        TRuta = new javax.swing.JTextField();
        THab = new javax.swing.JComboBox<>();
        NumHab = new javax.swing.JSpinner();
        jBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setText("Buscar Habitacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jButton2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton2.setText("Cambiar Tipo de Habitación");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        NumH.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        NumH.setText("Num. Habitacion");
        NumH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NumHMouseClicked(evt);
            }
        });
        getContentPane().add(NumH, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        TRuta.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        TRuta.setText("Usuario");
        TRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TRutaMouseClicked(evt);
            }
        });
        getContentPane().add(TRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 80, 30));

        getContentPane().add(THab, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));
        getContentPane().add(NumHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        jBack.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jBack.setText("Volver");
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pool.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:                   
        String routte = TRuta.getText();
        String numH = THab.getSelectedItem().toString();
        String nom = NumHab.getValue().toString();        
        String[] vec = new String[4];
        if(!routte.isEmpty()){
            try{                                                
                
                st = cn.createStatement();
                rs = st.executeQuery("SELECT * FROM habitacion(THab,NumH,Ruta,Cupo) VALUES('"+numH+"',?,'"+nom+"','"+routte+"')");
                
                while(rs.next()){
                    vec[0] = rs.getString(1);
                    vec[1] = rs.getString(2);
                    vec[2] = rs.getString(3);
                    vec[3] = rs.getString(4);
                }                
                TRuta.setText(vec[4]);                                                                
                JOptionPane.showMessageDialog(null,"Modificaste exitosamente!");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
        }else{
            JOptionPane.showMessageDialog(null,"ERROR! HAY ESPACIOS VACIOS");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TRutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TRutaMouseClicked
        // TODO add your handling code here:
        TRuta.setText("");
    }//GEN-LAST:event_TRutaMouseClicked

    private void NumHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NumHMouseClicked
        // TODO add your handling code here:
        NumH.setText("");
    }//GEN-LAST:event_NumHMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:                        
        String numH = NumH.getText();
        String tHab = NumHab.getValue().toString();
        String routte = TRuta.getText();                        
                
            try{                                                
                st = cn.createStatement();
                rs = st.executeQuery("SELECT NumH FROM habitacion ");
                
                while(rs.next()){
                    THab.addItem(rs.getString(1)); 
                    NumH.setText(rs.getString(3));
                    TRuta.setText(rs.getString(4));
                }                
                
                JOptionPane.showMessageDialog(null,"Modificaste exitosamente!");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        AI interfaz = new AI();
        interfaz.setLocationRelativeTo(null);
        interfaz.setVisible(true);
        interfaz.setSize(700,500);
        this.setVisible(false);
    }//GEN-LAST:event_jBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminModHab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminModHab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminModHab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminModHab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminModHab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NumH;
    private javax.swing.JSpinner NumHab;
    private javax.swing.JComboBox<String> THab;
    private javax.swing.JTextField TRuta;
    private javax.swing.JButton jBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
