package hotel;

import java.awt.Image;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xjlop
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    Conexion cc = new Conexion();
    Connection cn =  cc.conexion();
    ResultSet rs;
    Statement st;
    DefaultTableModel modelo = new DefaultTableModel();
    String[] datos = new String[4];
    
    public Consultas() {
        initComponents();
        this.setSize(700,560);
        Reservar.setEnabled(false);
        Tabla.setModel(modelo);
        modelo.addColumn("Numero de Habitacion");
        modelo.addColumn("Tipo de Habitacion");
        modelo.addColumn("Cupo");
        modelo.addColumn("Piso");
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT NumH,THab,Cupo,Piso FROM habitacion WHERE Cupo = 0;");
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                if(rs.getString(2).equals("1")){
                    datos[1] = "Hab.Sencilla";
                }
                if(rs.getString(2).equals("2")){
                     datos[1] = "Hab.Doble";
                }
                if(rs.getString(2).equals("3")){
                     datos[1] = "Hab.Triple";
                }
                if(rs.getString(3).equals("0")){
                    datos[2] = "Desocupado";
                }
                datos[3] = rs.getString(4);
                modelo.addRow(datos);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Reservar = new javax.swing.JButton();
        Regresar = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FechaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                FechaMouseReleased(evt);
            }
        });
        Fecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                FechaPropertyChange(evt);
            }
        });
        Fecha.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                FechaVetoableChange(evt);
            }
        });
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 120, -1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, 130));

        Reservar.setText("Reservar");
        Reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarActionPerformed(evt);
            }
        });
        getContentPane().add(Reservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 110, 30));

        Regresar.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        Regresar.setForeground(new java.awt.Color(255, 0, 0));
        Regresar.setText("BACK");
        Regresar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RegresarMouseReleased(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 100, 50));

        Imagen.setBorder(new javax.swing.border.MatteBorder(null));
        Imagen.setOpaque(true);
        getContentPane().add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 350, 170));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        jLabel2.setText("VISTA PREVIA HABITACION :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 370, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Selecciona Fecha para habilitar \"Resevar\"");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 260, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        jMenu1.setText("CHECK IN/CONSULTA");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("DISTRIBUCION DE HABITACIONES");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        String[] weas = new String[4];
        String ruta = "";
        int row = Tabla.getSelectedRow();
        weas[0] = (String)Tabla.getValueAt(row, 0);
       
        if(Tabla.getValueAt(row, 1).equals("Hab.Sencilla")){
             weas[1] = "1";
        }
        if(Tabla.getValueAt(row, 1).equals("Hab.Doble")){
             weas[1] = "2";
        }
        if(Tabla.getValueAt(row, 1).equals("Hab.Triple")){
             weas[1] = "3";
        }
        weas[2] = (String)Tabla.getValueAt(row, 2);
        weas[3] = (String)Tabla.getValueAt(row, 3);
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT Ruta FROM tipohab WHERE THab = " + weas[1]);
            while(rs.next()){
                
                ruta = rs.getString(1);
            }
            System.out.println(ruta);
            Image l = new ImageIcon(this.getClass().getResource("/Imagenes/"+ruta)).getImage().getScaledInstance(Imagen.getWidth(),
                Imagen.getHeight(), Image.SCALE_SMOOTH);;
            ImageIcon ii = new ImageIcon(l);
            Imagen.setIcon(ii);
            datos= weas;
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error");
        }
        //SELECT Ruta FROM habitacion WHERE NumH = "+weas[0]+"
    }//GEN-LAST:event_TablaMouseClicked

    private void ReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarActionPerformed
        String dob = ""+Fecha.getDate();
        SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd"); 
        dob = Date_Format.format(Fecha.getDate());
        this.setVisible(false);
        Altas altas = new Altas(dob,datos[0]);
        altas.setSize(710,530);
        altas.setLocationRelativeTo(null);
        altas.setVisible(true);
    }//GEN-LAST:event_ReservarActionPerformed

    private void FechaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FechaMouseReleased

    }//GEN-LAST:event_FechaMouseReleased

    private void FechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FechaMouseClicked

    }//GEN-LAST:event_FechaMouseClicked

    private void FechaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_FechaVetoableChange

    }//GEN-LAST:event_FechaVetoableChange

    private void FechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_FechaPropertyChange
        String dob = ""+Fecha.getDate();
        SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd"); 
        //dob = Date_Format.format(Fecha.getDate());
        //System.out.println(dob);
        if(!dob.equals("")){
            Reservar.setEnabled(true);
        }
    }//GEN-LAST:event_FechaPropertyChange

    private void RegresarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseReleased
        UI ui = new UI();
        this.setVisible(false);
        ui.setVisible(true);
        ui.setSize(700, 500);
        ui.setResizable(false);
        ui.setLocationRelativeTo(null);
    }//GEN-LAST:event_RegresarMouseReleased

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       Consultas UI=new Consultas();
       this.setVisible(false);
       UI.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
       Piso1 UI=new Piso1();
       this.setVisible(false);
       UI.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Regresar;
    private javax.swing.JButton Reservar;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
