/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.awt.Image;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xjlop
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    Conexion cc = new Conexion();
    Connection cn =  cc.conexion();
    ResultSet rs;
    Statement st;
    DefaultTableModel modelo = new DefaultTableModel();
    String[] datos = new String[3];
    
    public Consultas() {
        initComponents();
        Reservar.setEnabled(false);
        Tabla.setModel(modelo);
        modelo.addColumn("NumH");
        modelo.addColumn("THab");
        modelo.addColumn("Cupo");
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT NumH,THab,Cupo FROM habitacion WHERE Cupo = 0;");
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                modelo.addRow(datos);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Imagen = new javax.swing.JLabel();
        Reservar = new javax.swing.JButton();
        Regresar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FechaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                FechaMouseReleased(evt);
            }
        });
        Fecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                FechaPropertyChange(evt);
            }
        });
        Fecha.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                FechaVetoableChange(evt);
            }
        });
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 120, -1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, 130));

        Imagen.setText("Imagen");
        getContentPane().add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 170, 100));

        Reservar.setText("Reservar");
        Reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarActionPerformed(evt);
            }
        });
        getContentPane().add(Reservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 110, -1));

        Regresar.setText("Regresar");
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RegresarMouseReleased(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        String[] weas = new String[3];
        String ruta = "";
        int row = Tabla.getSelectedRow();
        weas[0] = (String)Tabla.getValueAt(row, 0);
        weas[1] = (String)Tabla.getValueAt(row, 1);
        weas[2] = (String)Tabla.getValueAt(row, 2);
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT Ruta FROM habitacion WHERE NumH = " + weas[0]);
            while(rs.next()){
                ruta = rs.getString(1);
            }
            System.out.println(ruta);
            Image l = new ImageIcon(this.getClass().getResource("/Imagenes/"+ruta)).getImage();
            ImageIcon ii = new ImageIcon(l);
            Imagen.setIcon(ii);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error");
        }
        //SELECT Ruta FROM habitacion WHERE NumH = "+weas[0]+"
    }//GEN-LAST:event_TablaMouseClicked

    private void ReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarActionPerformed
        String dob = ""+Fecha.getDate();
        SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd"); 
        dob = Date_Format.format(Fecha.getDate());
        this.setVisible(false);
        Altas altas = new Altas(dob,datos[0]);
        altas.setSize(700,500);
        altas.setLocationRelativeTo(null);
        altas.setVisible(true);
    }//GEN-LAST:event_ReservarActionPerformed

    private void FechaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FechaMouseReleased

    }//GEN-LAST:event_FechaMouseReleased

    private void FechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FechaMouseClicked

    }//GEN-LAST:event_FechaMouseClicked

    private void FechaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_FechaVetoableChange

    }//GEN-LAST:event_FechaVetoableChange

    private void FechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_FechaPropertyChange
        String dob = ""+Fecha.getDate();
        SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd"); 
        //dob = Date_Format.format(Fecha.getDate());
        //System.out.println(dob);
        if(!dob.equals("")){
            Reservar.setEnabled(true);
        }
    }//GEN-LAST:event_FechaPropertyChange

    private void RegresarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseReleased
        UI ui = new UI();
        this.setVisible(false);
        ui.setVisible(true);
        ui.setSize(700, 500);
        ui.setResizable(false);
        ui.setLocationRelativeTo(null);
    }//GEN-LAST:event_RegresarMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Regresar;
    private javax.swing.JButton Reservar;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
