/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class Galeria extends javax.swing.JFrame {

    /**
     * Creates new form Galeria
     */
    Conexion cc=new Conexion();
    Connection cn = cc.conexion();
    int max=0;
    int cont=1;
    public Galeria() {
        initComponents();
        this.setSize(1280,720);
        this.setLocationRelativeTo(null);
        String cad="";
        try{
            ResultSet RS;
            Statement ST;
            ST = cn.createStatement();
            RS=ST.executeQuery("SELECT count(*) from galeria ");
            while(RS.next()){
                    max=RS.getInt(1);
            }
            ST= cn.createStatement();
            RS= ST.executeQuery("SELECT * from galeria where id=1");
            while(RS.next()){
                cad=RS.getString(1);
                
            }
            Image i = new ImageIcon(this.getClass().getResource("/Imagenes/"+cad)).getImage();
            ImageIcon II=new ImageIcon(i);
            jLabel1.setIcon(II);
        
            
        }catch(SQLException E){
            JOptionPane.showMessageDialog(null, "error");
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 990, 690));

        jButton1.setText("SIGUIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 360, -1, -1));

        jButton2.setText("ANTERIOR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cad="";
        cont++;
        if(cont>max){
            cont=1;
        }
        try{
            ResultSet RS;
            Statement ST;
            ST= cn.createStatement();
            RS= ST.executeQuery("SELECT * from galeria where id="+cont);
            while(RS.next()){
                cad=RS.getString(1);
                
            }
            Image i = new ImageIcon(this.getClass().getResource("/Imagenes/"+cad)).getImage();
            ImageIcon II=new ImageIcon(i);
            jLabel1.setIcon(II);
        
            
        }catch(SQLException E){
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String cad="";
        cont--;
        if(cont<1){
            cont=max;
        }
        try{
            ResultSet RS;
            Statement ST;
            ST= cn.createStatement();
            RS= ST.executeQuery("SELECT * from galeria where id="+cont);
            while(RS.next()){
                cad=RS.getString(1);
                
            }
            Image i = new ImageIcon(this.getClass().getResource("/Imagenes/"+cad)).getImage();
            ImageIcon II=new ImageIcon(i);
            jLabel1.setIcon(II);
        
            
        }catch(SQLException E){
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Galeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Galeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Galeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Galeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Galeria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
