/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author xjlop
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Conexion cc = new Conexion();
    Connection cn = cc.conexion();
    public Login() {
        initComponents();
        this.dispose();
        this.setUndecorated(true);
        this.setBackground(new Color(1.0f,1.0f,1.0f,0f));
        this.setSize(700,500);
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        User.setOpaque(false);
        User.setBorder(null);
        User.setForeground(Color.white);
        Password.setForeground(Color.white);
        Password.setOpaque(false);
        Password.setBorder(null);
        Image l = new ImageIcon(this.getClass().getResource("/Imagenes/BackLogin.png")).getImage();
        ImageIcon ii = new ImageIcon(l);
        jLabel1.setIcon(ii);
        try {
            Font font = Font.createFont(Font.TRUETYPE_FONT, new File(this.getClass().getResource("/Fuentes/SFProDisplay-Bold.ttf").getFile())).deriveFont(16f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(font);
            User.setFont(font);
        } catch (IOException e) {
            e.printStackTrace();
        } catch(FontFormatException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        User = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        Salir = new javax.swing.JLabel();
        Ingresar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        User.setText("Usuario");
        User.setPreferredSize(new java.awt.Dimension(110, 20));
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMouseClicked(evt);
            }
        });
        getContentPane().add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        Password.setText("jPasswordField1");
        Password.setPreferredSize(new java.awt.Dimension(110, 20));
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordMouseClicked(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SalirMouseReleased(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 70));

        Ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ingresar.png"))); // NOI18N
        Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresarMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                IngresarMouseReleased(evt);
            }
        });
        getContentPane().add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 140, 70));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseClicked
        User.setText("");
    }//GEN-LAST:event_UserMouseClicked

    private void PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseClicked
        Password.setText("");
    }//GEN-LAST:event_PasswordMouseClicked

    private void IngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarMouseClicked

    private void IngresarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMouseReleased
        String Usuario = User.getText();
        String password = Password.getText();
        String[] datos = new String[2];
        Statement st;
        ResultSet rs;
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT Usr,Pass FROM credenciales WHERE Usr = '" + Usuario + "' && Pass = MD5('" + password + "'); ");
            while(rs.next()){
                for(int i = 0; i < datos.length; i++)
                    datos[i] = rs.getString(i+1);
            }
            String passMD5 = MD5(password);
            if(Usuario.equals(datos[0]) && passMD5.equals(datos[1])){
                if(datos[0].equals("root")){
                    JOptionPane.showMessageDialog(null, "Logged as root");
                    AI interfaz = new AI();
                    interfaz.setLocationRelativeTo(null);
                    interfaz.setVisible(true);
                    interfaz.setSize(700,500);
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null, "Login exitoso");
                    UI interfaz = new UI();
                    interfaz.setLocationRelativeTo(null);
                    interfaz.setVisible(true);
                    interfaz.setSize(700,500);
                    this.setVisible(false);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Las credenciales son invalidas");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Algo fallo en la consulta \n" + e);
        }catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IngresarMouseReleased

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseReleased
        System.exit(0);
    }//GEN-LAST:event_SalirMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
   public static String MD5(String s) throws Exception {
        MessageDigest m=MessageDigest.getInstance("MD5");
        m.update(s.getBytes(),0,s.length());     
        return new BigInteger(1,m.digest()).toString(16); 
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ingresar;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Salir;
    private javax.swing.JTextField User;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
