/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotel;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Recibo extends javax.swing.JFrame {
    Conexion cc = new Conexion();
    Connection cn = cc.conexion();
    Statement st;
    ResultSet rs;
    /** Creates new form Recibo */
    public Recibo(String Fecha1,String Fecha2,String Nombre) {
        initComponents();
        Image l;
        l = new ImageIcon(this.getClass().getResource("/Imagenes/FondoPisos.jpg")).getImage().getScaledInstance(FONDO.getWidth(),
        FONDO.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon I = new ImageIcon(l);
        FONDO.setIcon(I);
        
          Image ii;
        ii = new ImageIcon(this.getClass().getResource("/Imagenes/Logo.png")).getImage().getScaledInstance(jLabel15.getWidth(),
        jLabel15.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon II = new ImageIcon(ii);
        jLabel15.setIcon(II);
        int aleatorio = (int)(Math.random() * (1000 - 1 + 1) + 1);
        this.NmRecibo.setText(Integer.toString(aleatorio));
        this.Fecha1.setText(Fecha1);
        this.FechaSal.setText(Fecha2);
        this.Cliente.setText(Nombre);
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT Nombre,NumH,CiudaddeOrigen,Tpersonas FROM Customers");
            while(rs.next()){
                if(rs.getString(1).equals(this.Cliente.getText())){
                   this.Habitacion.setText(rs.getString(2));
                   this.CDORIGEN.setText(rs.getString(3));
                   this.Ocupantes.setText(rs.getString(4));
                }
            }
            
            st = cn.createStatement();
            rs = st.executeQuery("SELECT THab,NumH,Piso FROM habitacion");
            while(rs.next()){
                if(rs.getString(2).equals(this.Habitacion.getText())){
                   this.Thab.setText(rs.getString(1));
                   this.piso.setText(rs.getString(3));
                }
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error");
        }
        
          if(this.Thab.getText().equals("1")){
           this.Thab.setText("Hab. Simple");
           this.limite.setText("1");
          }
            if(this.Thab.getText().equals("2")){
           this.Thab.setText("Hab. Doble");
           this.limite.setText("2");
          }
             if(this.Thab.getText().equals("3")){
           this.Thab.setText("Hab. Triple");
           this.limite.setText("3");
          }
             
          checkeo();
    }
    
    
    
    
    
    
    public Recibo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        NmRecibo = new javax.swing.JTextField();
        Cliente = new javax.swing.JTextField();
        CDORIGEN = new javax.swing.JTextField();
        Fecha1 = new javax.swing.JTextField();
        FechaSal = new javax.swing.JTextField();
        Habitacion = new javax.swing.JTextField();
        Thab = new javax.swing.JTextField();
        Ocupantes = new javax.swing.JTextField();
        limite = new javax.swing.JTextField();
        piso = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        jLabel1.setText("RECIBO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 107, -1));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 3, 14)); // NOI18N
        jLabel2.setText("\"ASEGURA TU VERANO\"");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, 306, -1));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel3.setText("CLIENTE: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, 130, -1));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel4.setText("PISO: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel5.setText("CIUDAD ORIGEN: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 137, -1, -1));

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel6.setText("FECHA INGRESO: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel7.setText("FECHA SALIDA: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel8.setText("NUM. HABITACION: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel9.setText("TIPO DE HABITACION: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        jLabel10.setText("HOTEL JESA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, -1, -1));

        jLabel11.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel11.setText("LIMITE HAB. : ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel12.setText("TOTAL OCUPANTES: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel13.setText("PERSONAS EXTRAS: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jLabel14.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        jLabel14.setText("Num.Recibo : ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 130, 100));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("BACK MENU");
        jLabel16.setOpaque(true);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 160, -1));

        NmRecibo.setEditable(false);
        NmRecibo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NmRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NmReciboActionPerformed(evt);
            }
        });
        getContentPane().add(NmRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 90, -1));

        Cliente.setEditable(false);
        Cliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 180, -1));

        CDORIGEN.setEditable(false);
        CDORIGEN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(CDORIGEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 110, -1));

        Fecha1.setEditable(false);
        Fecha1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 110, -1));

        FechaSal.setEditable(false);
        FechaSal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(FechaSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 130, -1));

        Habitacion.setEditable(false);
        Habitacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 80, -1));

        Thab.setEditable(false);
        Thab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Thab, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 150, -1));

        Ocupantes.setEditable(false);
        Ocupantes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Ocupantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 70, -1));

        limite.setEditable(false);
        limite.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(limite, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 80, -1));

        piso.setEditable(false);
        piso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(piso, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 90, -1));

        jCheckBox1.setText("1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        jCheckBox2.setText("2");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        FONDO.setBackground(new java.awt.Color(204, 204, 204));
        FONDO.setOpaque(true);
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 730, 398));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NmReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NmReciboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NmReciboActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        UI ui=new UI();
        this.setVisible(false);
        ui.setVisible(true);
        ui.setSize(700, 500);
        ui.setResizable(false);
        ui.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recibo().setVisible(true);
            }
        });
    }
    
    private void checkeo(){
        String cupo=this.Ocupantes.getText();
        String lim=this.limite.getText();
        int totalcupo=Integer.parseInt(cupo);
        int limites=Integer.parseInt(lim);
        int res=totalcupo-limites;
        System.out.println(res);
        if(res==1){
            this.jCheckBox1.isSelected();
            this.jCheckBox1.setSelected(true);
            this.jCheckBox2.setVisible(false);
        }if(res==2){
            this.jCheckBox2.isSelected();
            this.jCheckBox2.setSelected(true);
            this.jCheckBox1.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CDORIGEN;
    private javax.swing.JTextField Cliente;
    private javax.swing.JLabel FONDO;
    private javax.swing.JTextField Fecha1;
    private javax.swing.JTextField FechaSal;
    private javax.swing.JTextField Habitacion;
    private javax.swing.JTextField NmRecibo;
    private javax.swing.JTextField Ocupantes;
    private javax.swing.JTextField Thab;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField limite;
    private javax.swing.JTextField piso;
    // End of variables declaration//GEN-END:variables

}
