/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;

/**
 *
 * @author xjlop
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    
    public UI() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Consultas = new javax.swing.JLabel();
        Salir = new javax.swing.JLabel();
        Bajas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Consultas.setText("Consultas");
        Consultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultasMouseClicked(evt);
            }
        });
        getContentPane().add(Consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 140, 120));

        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SalirMouseReleased(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 140, 120));

        Bajas.setText("Bajas");
        Bajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BajasMouseReleased(evt);
            }
        });
        getContentPane().add(Bajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BajasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BajasMouseReleased
        Bajas bajas = new Bajas();
        bajas.setLocationRelativeTo(null);
        bajas.setSize(700, 500);
        bajas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BajasMouseReleased

    private void SalirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseReleased
        System.exit(0);
    }//GEN-LAST:event_SalirMouseReleased

    private void ConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultasMouseClicked
        Consultas consultas = new Consultas();
        this.setVisible(false);
        consultas.setVisible(true);
        consultas.setLocationRelativeTo(null);
        consultas.setSize(700,500);
        consultas.setResizable(false);
    }//GEN-LAST:event_ConsultasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bajas;
    private javax.swing.JLabel Consultas;
    private javax.swing.JLabel Salir;
    // End of variables declaration//GEN-END:variables
}
